# Generated by Django 4.1 on 2023-10-27 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('text', models.TextField(verbose_name='Comentario sobre el servicio o producto')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso del comentario')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización de los comentarios')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
