# Generated by Django 4.1 on 2023-11-22 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Nombre de producto')),
                ('text', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects', verbose_name='imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
